"""initial schema: market_data, portfolios, positions, risk_metrics, anomalies, alerts

Revision ID: 0001
Revises:
Create Date: 2026-09-01

Hand-written (not autogenerated) so constraint/index names and the cross-dialect
column types are explicit and reviewable. Types use ``with_variant`` where the
Postgres and SQLite representations differ, so this same migration runs under both.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Auto-incrementing key type: BIGINT on Postgres, INTEGER on SQLite.
BIGINT_ID = sa.BigInteger().with_variant(sa.Integer(), "sqlite")
MONEY = sa.Numeric(18, 6)
JSON_TYPE = sa.JSON().with_variant(JSONB(), "postgresql")


def upgrade() -> None:
    # ── market_data ─────────────────────────────────────────
    op.create_table(
        "market_data",
        sa.Column("id", BIGINT_ID, primary_key=True, autoincrement=True),
        sa.Column("ticker", sa.String(16), nullable=False),
        sa.Column("date", sa.Date, nullable=False),
        sa.Column("open", MONEY, nullable=False),
        sa.Column("high", MONEY, nullable=False),
        sa.Column("low", MONEY, nullable=False),
        sa.Column("close", MONEY, nullable=False),
        sa.Column("adjusted_close", MONEY, nullable=False),
        sa.Column("volume", sa.BigInteger, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("ticker", "date", name="uq_market_data_ticker_date"),
        sa.CheckConstraint("high >= low", name="ck_market_data_high_ge_low"),
        sa.CheckConstraint(
            "open > 0 AND high > 0 AND low > 0 AND close > 0 AND adjusted_close > 0",
            name="ck_market_data_positive_prices",
        ),
        sa.CheckConstraint("volume >= 0", name="ck_market_data_volume_nonneg"),
    )
    op.create_index("ix_market_data_ticker_date", "market_data", ["ticker", "date"])

    # ── portfolios ──────────────────────────────────────────
    op.create_table(
        "portfolios",
        sa.Column("id", BIGINT_ID, primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=False, unique=True),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )

    # ── positions ───────────────────────────────────────────
    op.create_table(
        "positions",
        sa.Column("id", BIGINT_ID, primary_key=True, autoincrement=True),
        sa.Column(
            "portfolio_id",
            BIGINT_ID,
            sa.ForeignKey("portfolios.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("ticker", sa.String(16), nullable=False),
        sa.Column("quantity", MONEY, nullable=False),
        sa.Column("average_price", MONEY, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("portfolio_id", "ticker", name="uq_position_portfolio_ticker"),
        sa.CheckConstraint("quantity <> 0", name="ck_position_quantity_nonzero"),
    )
    op.create_index("ix_position_portfolio_id", "positions", ["portfolio_id"])

    # ── risk_metrics ────────────────────────────────────────
    op.create_table(
        "risk_metrics",
        sa.Column("id", BIGINT_ID, primary_key=True, autoincrement=True),
        sa.Column(
            "portfolio_id",
            BIGINT_ID,
            sa.ForeignKey("portfolios.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("calculation_date", sa.Date, nullable=False),
        sa.Column("confidence_level", sa.Numeric(4, 3), nullable=False),
        sa.Column("var", MONEY, nullable=True),
        sa.Column("parametric_var", MONEY, nullable=True),
        sa.Column("volatility_annualized", MONEY, nullable=True),
        sa.Column("max_drawdown", MONEY, nullable=True),
        sa.Column("exposure_gross", MONEY, nullable=True),
        sa.Column("exposure_net", MONEY, nullable=True),
        sa.Column("stress_loss", MONEY, nullable=True),
        sa.Column("method", sa.String(64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index(
        "ix_risk_metrics_portfolio_date", "risk_metrics", ["portfolio_id", "calculation_date"]
    )

    # ── anomalies ───────────────────────────────────────────
    op.create_table(
        "anomalies",
        sa.Column("id", BIGINT_ID, primary_key=True, autoincrement=True),
        sa.Column(
            "portfolio_id",
            BIGINT_ID,
            sa.ForeignKey("portfolios.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("ticker", sa.String(16), nullable=False),
        sa.Column("date", sa.Date, nullable=False),
        sa.Column("anomaly_score", sa.Numeric(18, 8), nullable=False),
        sa.Column("anomaly_type", sa.String(64), nullable=False),
        sa.Column("features", JSON_TYPE, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_anomalies_ticker_date", "anomalies", ["ticker", "date"])
    op.create_index("ix_anomalies_portfolio_id", "anomalies", ["portfolio_id"])

    # ── alerts ──────────────────────────────────────────────
    op.create_table(
        "alerts",
        sa.Column("id", BIGINT_ID, primary_key=True, autoincrement=True),
        sa.Column(
            "portfolio_id",
            BIGINT_ID,
            sa.ForeignKey("portfolios.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("alert_type", sa.String(64), nullable=False),
        sa.Column("severity", sa.String(16), nullable=False),
        sa.Column("message", sa.Text, nullable=False),
        sa.Column("metric_value", MONEY, nullable=True),
        sa.Column("threshold", MONEY, nullable=True),
        sa.Column("dedup_key", sa.String(255), nullable=False),
        sa.Column("acknowledged", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("dedup_key", name="uq_alert_dedup"),
    )
    op.create_index("ix_alerts_portfolio_ack", "alerts", ["portfolio_id", "acknowledged"])


def downgrade() -> None:
    op.drop_index("ix_alerts_portfolio_ack", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_anomalies_portfolio_id", table_name="anomalies")
    op.drop_index("ix_anomalies_ticker_date", table_name="anomalies")
    op.drop_table("anomalies")
    op.drop_index("ix_risk_metrics_portfolio_date", table_name="risk_metrics")
    op.drop_table("risk_metrics")
    op.drop_index("ix_position_portfolio_id", table_name="positions")
    op.drop_table("positions")
    op.drop_table("portfolios")
    op.drop_index("ix_market_data_ticker_date", table_name="market_data")
    op.drop_table("market_data")
